version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://pguser:pgpassword@db:5432/pgdb
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT} 
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate deploy && node dist/server.js"

volumes:
  pgdata: 